name = "TNAD"
uuid = "7fc4d430-46d8-4b40-bf23-f8a1aee54bb9"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez@bsc.es>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
